version: "3"
services:
  app:
    build: app
    environment:
     - DD_AGENT_HOST=datadog # used by the app to initialize the Datadog library
  datadog:
    build: datadog
    environment:
     - DD_API_KEY=
     - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
     - DD_SITE="us5.datadoghq.com"
    links:
     - app
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
